import gql from 'graphql-tag';
import { Resolvers } from '../generated/types';

// graphql schema definition and its resolvers
export const typeDefs = gql`
  type Query {
    userByEmail(email: ID!): User
  }

  type Mutation {
    createUser(input: CreateUserInput!): User
  }

  input CreateUserInput {
    name: String
    email: String!
  }

  type User @key(fields: "id") {
    id: ID!
    name: String
    email: String!
  }
`;

// resolvers for above schema
// context is what we passed when we created apollo server in server.ts file
// these resolvers are fully typed based on the context and the schema definition
// the types are automatically generated by running "yarn generated"
export const resolvers: Resolvers = {
  Query: {
    // The idea with the resolvers are to keep it as lean as possible. no logic should be added here and instead be done in the service method
    // here we simply get the arguments and call the service method. it should determine any logic such as permissions, validations, etc
    userByEmail: (_, args, context) => context.User.userByEmail(args.email)
  },
  Mutation: {
    createUser: (_, args, context) => context.User.createUser(args.input)
  },
  User: {
    __resolveReference: (user, context) => context.User.userByEmail(user.id)
  }
};
